# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

parameters:
  run_php:
    type: boolean
    default: false
  run_perf:
    type: boolean
    default: false
  run_admin:
    type: boolean
    default: false

jobs:
  "php82-sqlite3":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: sqlite
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php82-mariadb10":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: mariadb
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mariadb:10
        environment:
          MARIADB_ROOT_PASSWORD: rootpw
          MARIADB_USER: pagible
          MARIADB_PASSWORD: pagible
          MARIADB_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php82-mysql8":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: mysql
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: pagible
          MYSQL_PASSWORD: pagible
          MYSQL_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php82-pgsql14":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: pgsql
          DB_HOST: "127.0.0.1"
          DB_PORT: 5432
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: postgres:14
        environment:
          POSTGRES_PASSWORD: pagible
          POSTGRES_USER: pagible
          POSTGRES_DB: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 5432 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php82-mssql17":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: sqlsrv
          DB_HOST: "127.0.0.1"
          DB_PORT: 1433
          DB_USERNAME: SA
          DB_PASSWORD: S3c0r3P4ss
          DB_DATABASE: cms
      - image: aimeos/ci-mssql-fts:2017
        environment:
          SA_PASSWORD: S3c0r3P4ss
          ACCEPT_EULA: Y
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: echo "CREATE DATABASE cms;" > sqlserver.sql; for i in `seq 1 10`; do /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U SA -P 'S3c0r3P4ss' -i sqlserver.sql && exit 0; sleep 3; done
      - run: ./vendor/bin/phpunit

  "php85-sqlite":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: sqlite
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php85-mariadb":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: mariadb
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mariadb:latest
        environment:
          MARIADB_ROOT_PASSWORD: rootpw
          MARIADB_USER: pagible
          MARIADB_PASSWORD: pagible
          MARIADB_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php85-mysql":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: mysql
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: pagible
          MYSQL_PASSWORD: pagible
          MYSQL_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php85-pgsql":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: pgsql
          DB_HOST: "127.0.0.1"
          DB_PORT: 5432
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: postgres:18
        environment:
          POSTGRES_PASSWORD: pagible
          POSTGRES_USER: pagible
          POSTGRES_DB: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 5432 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php85-phpstan":
    docker:
      - image: aimeos/ci-php:8.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpstan --no-progress

  "admin-lint":
    docker:
      - image: cimg/node:lts
    working_directory: ~/project/admin/app
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - admin-{{ checksum "package-lock.json" }}
      - run: npm ci --cache ~/.npm
      - save_cache:
          key: admin-{{ checksum "package-lock.json" }}
          paths:
            - ./.npm
      - run: npx eslint

  "admin-unit":
    docker:
      - image: cypress/browsers:latest
    working_directory: ~/project/admin/app
    parallelism: 3
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - admin-{{ checksum "package-lock.json" }}
      - run: npm ci --cache ~/.npm
      - save_cache:
          key: admin-{{ checksum "package-lock.json" }}
          paths:
            - ./.npm
            - ~/.cache/Cypress
      - run:
          name: Run component tests
          command: |
            case $CIRCLE_NODE_INDEX in
              0) SPECS="tests/fields/**/*.cy.{js,ts}" ;;
              1) SPECS="tests/components/**/*.cy.{js,ts}" ;;
              2) SPECS="tests/*.cy.{js,ts},tests/js/**/*.cy.{js,ts},tests/views/**/*.cy.{js,ts}" ;;
            esac
            npx cypress run --component --spec "$SPECS"

  "admin-e2e":
    docker:
      - image: cypress/browsers:latest
    working_directory: ~/project/admin/app
    parallelism: 4
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - admin-{{ checksum "package-lock.json" }}
      - run: npm ci --cache ~/.npm
      - save_cache:
          key: admin-{{ checksum "package-lock.json" }}
          paths:
            - ./.npm
            - ~/.cache/Cypress
      - run: npm run build
      - run: npx start-server-and-test preview http://localhost:4173 \
          "npx cypress run --spec $(circleci tests glob 'cypress/e2e/**/*.cy.{js,ts}' | circleci tests split --split-by=timings | tr '\n' ',')"
      - store_artifacts:
          path: cypress

  "perf-sqlite":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: sqlite
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit --group benchmark

  "perf-mariadb":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: mariadb
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mariadb:latest
        environment:
          MARIADB_ROOT_PASSWORD: rootpw
          MARIADB_USER: pagible
          MARIADB_PASSWORD: pagible
          MARIADB_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit --group benchmark

  "perf-mysql":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: mysql
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: pagible
          MYSQL_PASSWORD: pagible
          MYSQL_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit --group benchmark

  "perf-pgsql":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: pgsql
          DB_HOST: "127.0.0.1"
          DB_PORT: 5432
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: postgres:18
        environment:
          POSTGRES_PASSWORD: pagible
          POSTGRES_USER: pagible
          POSTGRES_DB: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 5432 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit --group benchmark

  "perf-mssql":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: sqlsrv
          DB_HOST: "127.0.0.1"
          DB_PORT: 1433
          DB_USERNAME: SA
          DB_PASSWORD: S3c0r3P4ss
          DB_DATABASE: cms
      - image: aimeos/ci-mssql-fts:2017
        environment:
          SA_PASSWORD: S3c0r3P4ss
          ACCEPT_EULA: Y
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: echo "CREATE DATABASE cms;" > sqlserver.sql; for i in `seq 1 10`; do /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U SA -P 'S3c0r3P4ss' -i sqlserver.sql && exit 0; sleep 3; done
      - run: ./vendor/bin/phpunit --group benchmark

workflows:
  version: 2
  php:
    when: << pipeline.parameters.run_php >>
    jobs:
#      - "php85-phpstan"
#      - "php82-sqlite3":
#          requires: ["php85-phpstan"]
#      - "php82-mariadb10":
#          requires: ["php85-phpstan"]
#      - "php82-mysql8":
#          requires: ["php85-phpstan"]
#      - "php82-pgsql14":
#          requires: ["php85-phpstan"]
#      - "php82-mssql17":
#          requires: ["php85-phpstan"]
#      - "php85-sqlite":
#          requires: ["php85-phpstan"]
#      - "php85-mariadb":
#          requires: ["php85-phpstan"]
#      - "php85-mysql":
#          requires: ["php85-phpstan"]
#      - "php85-pgsql":
#          requires: ["php85-phpstan"]
      - "perf-sqlite"
#          requires: ["php82-sqlite3", "php85-sqlite"]
      - "perf-mariadb"
#          requires: ["php82-mariadb10", "php85-mariadb"]
      - "perf-mysql"
#          requires: ["php82-mysql8", "php85-mysql"]
      - "perf-pgsql"
#          requires: ["php82-pgsql14", "php85-pgsql"]
      - "perf-mssql"
#          requires: ["php82-mssql17"]
  admin:
    when: << pipeline.parameters.run_admin >>
    jobs:
      - "admin-lint"
      - "admin-unit":
          requires: ["admin-lint"]
      - "admin-e2e":
          requires: ["admin-lint"]
